# First home assignment Social Data Science

Submit your solution by email to submission@cssh.rwth-aachen.de until 23.59pm on Wednesday, November 28th!
Use "[SDS] Submission Home Assignment 1" as the email subject.

You can (and should!) submit solutions in teams of up to three members.
Please denote all members of the team with their student id and full name in the notebook as well as in the email body. Put all team members in email CC when submitting. Please submit only one email per team.

Cite ALL your sources for coding this home assignment. In case of plagiarism (copying solutions from other teams or from the internet) ALL team members will be expelled from the course without warning.


### Implement multiple linear regression by gradient descent
Your implementation should be based on numpy arrays. Your implementation can use functions from the numpy library.

Your function should have the signature
linear_regression_gd (X,y,learning_rate) and should return a tuple (mean_squared_error_of_solution, [list_of_optimum_parameters])
Here, X is a numpy array with the values of the explanatory variables, and y is an array with the dependent variable



In [27]:
import numpy as np

# Values for X and y from https://www.crashkurs-statistik.de/multiple-lineare-regression/ so we can check if calculations are correct
# We also added a row of 1s to X to get the bias term
y = np.array([47.1, 46.8, 49.3, 53.2, 47.7, 49.0, 50.6, 47.1, 51.7, 47.8])
X = np.array([[156.3, 158.9, 160.8, 179.6, 156.6, 165.1, 165.9, 156.7, 167.8, 160.8], 
             [62, 52, 83, 69, 74, 52, 77, 65, 79, 51], 
             [24, 34, 26, 51, 43, 33, 22, 21, 19, 34]])

In [28]:
# Setting up the matrixes
# Hacky way with two transpositions to get the bias term


X = X.T # transpose so input vectors are along the rows
X = np.c_[X, np.ones(X.shape[0])] # add bias term
X_Trans = np.array(X) # save the transposed version as X_Trans
X = np.array(X.T) # revert to "original" X with bias term

In [15]:
"""
Following function inspired by:
https://stackoverflow.com/questions/11479064/multiple-linear-regression-in-python/33381686
"""
#linreg = np.linalg.lstsq(X,y)[0]
#print(linreg)

# calculate the predictions
#print((X.dot(linreg)))

#pred = np.dot(X,linreg)

#mse = (np.square(y-pred)).mean(axis=0)

#print(mse)

def hackyRegression(X,y):
    linreg = np.linalg.lstsq(X,y)[0]
    pred = np.dot(X,linreg)
    mse = (np.square(y-pred)).mean(axis=0)
    print(linreg)
    return(mse, linreg)

hackyRegression(X_Trans,y)

[ 0.27856669  0.05510842 -0.02139347  0.66299483]


/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


(0.055353189623654334,
 array([ 0.27856669,  0.05510842, -0.02139347,  0.66299483]))

In [34]:
def gradientDescent(X,y,theta,alpha,m,numIterations):
    for i in range(0, numIterations):
        hypothesis = sum((np.dot(X, theta)))
        print(hypothesis)
        loss = hypothesis - y
        cost = np.sum(loss ** 2) / (2 * m)
        print("Iteration {0} | Cost: {1}".format(i, cost))
        for j in range(len(X)):
            gradient = (X_Trans[j].dot(loss) / m)
            theta = theta - alpha * gradient
    return theta

n, m = np.shape(X)
#print(theta)
#print(m, n)
numIterations = 100
alpha = 0.0001
theta = gradientDescent(X,y,theta,alpha,m,numIterations)
print(theta)

1.9290842761999332e+20
Iteration 0 | Cost: 1.8606830723409102e+40


ValueError: shapes (4,) and (10,) not aligned: 4 (dim 0) != 10 (dim 0)

In [29]:
def linear_regression_gd(X,y,learning_rate):
    

[[156.3 158.9 160.8 179.6 156.6 165.1 165.9 156.7 167.8 160.8]
 [ 62.   52.   83.   69.   74.   52.   77.   65.   79.   51. ]
 [ 24.   34.   26.   51.   43.   33.   22.   21.   19.   34. ]
 [  1.    1.    1.    1.    1.    1.    1.    1.    1.    1. ]]
[[156.3  62.   24.    1. ]
 [158.9  52.   34.    1. ]
 [160.8  83.   26.    1. ]
 [179.6  69.   51.    1. ]
 [156.6  74.   43.    1. ]
 [165.1  52.   33.    1. ]
 [165.9  77.   22.    1. ]
 [156.7  65.   21.    1. ]
 [167.8  79.   19.    1. ]
 [160.8  51.   34.    1. ]]


### Extend your previous code to implement Stochastic Gradient Descent
Your function should have the signature
linear_regression_sgd (X,y,learning_rate, batch_size)

### Load the quality of Government Dataset 
from here: https://www.qogdata.pol.gu.se/data/qog_bas_cs_jan18.csv.
The data is described here
load it into a pandas dataframe and select the following columns:
"cname","wdi_lifexp","wdi_popden","gle_cgdpc","bti_acp", "bti_pdi", "fh_pair", "al_ethnic","al_language","al_religion","bti_aar","vdem_gender","bti_ci","bti_foe","wdi_araland", "wdi_forest"


In [ ]:
import pandas as pd
url = "https://www.qogdata.pol.gu.se/data/qog_bas_cs_jan18.csv"
df = pd.read_csv(url)

# select specified columns
col = df[["cname","wdi_lifexp","wdi_popden","gle_cgdpc","bti_acp", "bti_pdi", "fh_pair", "al_ethnic","al_language","al_religion","bti_aar","vdem_gender","bti_ci","bti_foe","wdi_araland", "wdi_forest"]]
col.head()

### Compute the correlation of all other variables with the life expectancy (wdi_lifexp)

In [ ]:
col[col.columns[1:]].corr("pearson")["wdi_lifexp"]

### Apply your own implementations  (GD and SGD)
To model the life expectancy from the population density and GDP per capita.
Compare the results with what you get from scikit learn OR statsmodel libraries.

For this subtask, just remove all countries with missing values in any of these three variables.

In [ ]:
df2 = col.dropna()
df2.head()

### Build regression models to model the life expectancy (wdi_lifexp) in this dataset
from all other mentioned variables.
You can use scikit learn and/or statsmodels libraries for this task.
Standardize variables and fill in missing values appropriately.
Compare linear regression, Ridge regression and Lasso using k-fold-cross validation
Test several parameters for the regularized regressions.


In [ ]:
df3 = col.fillna(col.mean(numeric_only=True))
df3 = (df3.select_dtypes(exclude=['object']) - df3.mean(numeric_only=True)) / df3.std(numeric_only=True)


#import matplotlib.pyplot as plt
#df.plot.scatter(x="vdem_gender", y="wdi_lifexp")
x = df3[["wdi_popden","gle_cgdpc","bti_acp", "bti_pdi", "fh_pair", "al_ethnic","al_language","al_religion","bti_aar","vdem_gender","bti_ci","bti_foe","wdi_araland", "wdi_forest"]]
y = df3["wdi_lifexp"]

from sklearn import linear_model

# Lineare Regression
linreg = linear_model.LinearRegression()
linreg.fit(x,y)
print(linreg.coef_)

# Ridge Regression
ridgereg = linear_model.Ridge(alpha = 1.0)
ridgereg.fit(x,y)
print(ridgereg.coef_)

# Wild-West Regression (Lasso)
lassoreg = linear_model.Lasso(alpha=0.1)
lassoreg.fit(x,y)
print(lassoreg.coef_)

### Implement Forward and Backward Selection algorithms
And apply it to the (given subset of variables of the) Quality of Government dataset.
Compare the results of Forward and Backward selection with each other.
